name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ 7.4, 8.0, 8.1 ]
        dependencies:
          - "lowest"
          - "highest"

    name: PHP ${{ matrix.php }}
    steps:
    - name: Checkout amadeus-php
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php }}

    - name: Report PHP version
      run: php -v

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install

    - name: Update Dependencies
      if: ${{ matrix.dependencies == 'lowest' }}
      run: composer update --prefer-lowest --prefer-stable -n

    - name: Run phpstan
      run: vendor/bin/phpstan analyse src tests

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
