name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ 7.4, 8.0, 8.1 ]

    name: PHP ${{ matrix.php }}
    steps:
    - name: Checkout amadeus-php
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php }}

    - name: Report PHP version
      run: php -v

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --ignore-platform-reqs

    - name: Update dependencies
      run: composer update --ignore-platform-reqs

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse src tests --level 5

    - name: Run PHPUnit Test and Generate Code Coverage Report
      run: vendor/bin/phpunit --coverage-text tests

    - name: Run PHP-CS-Fixer for src
      if: ${{ matrix.php == '8.1' }}
      run: vendor/bin/php-cs-fixer fix src --dry-run --stop-on-violation

    - name: Run PHP-CS-Fixer for tests
      if: ${{ matrix.php == '8.1' }}
      run: vendor/bin/php-cs-fixer fix tests --dry-run --stop-on-violation