name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ 7.4 ]

    name: PHP ${{ matrix.php }}
    steps:
    - name: Checkout amadeus-php
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php }}

    - name: Report PHP version
      run: php -v

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --ignore-platform-reqs

    - name: Update dependencies
      run: composer update --ignore-platform-reqs

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse src tests

    - name: Run PHPUnit
      run: vendor/bin/phpunit tests
